<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ad2petritraceability" nsURI="ad2petritraceability" nsPrefix="ad2petritraceability">
  <eClassifiers xsi:type="ecore:EClass" name="Ad2petriTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonFinalNodeTraces" upperBound="-1" eType="//NodeToPlaceTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finalNodeTraces" upperBound="-1" eType="//FinalNodeTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityTraces" upperBound="-1" eType="//ActivityTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlFlowTraces" upperBound="-1" eType="//ControlFlowTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinNodeTraces" upperBound="-1" eType="//JoinNodeTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forkNodeTraces" upperBound="-1" eType="//ForkNodeTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityTrace" eSuperTypes="//Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalActivity">
      <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.model/ad/activitydiagram.ecore#//Activity"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="net">
      <eType xsi:type="ecore:EClass" href="../../fr.inria.diverse.sample.petrinetv1.model/model/petrinetv1.ecore#//Net"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToPlaceTrace" eSuperTypes="//Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalNode">
      <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.model/ad/activitydiagram.ecore#//ActivityNode"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="place">
      <eType xsi:type="ecore:EClass" href="../../fr.inria.diverse.sample.petrinetv1.model/model/petrinetv1.ecore#//Place"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalNodeTrace" eSuperTypes="//Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalNode">
      <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.model/ad/activitydiagram.ecore#//ActivityNode"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition">
      <eType xsi:type="ecore:EClass" href="../../fr.inria.diverse.sample.petrinetv1.model/model/petrinetv1.ecore#//Transition"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkOrJoinNodeTrace" abstract="true" eSuperTypes="//Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalNode">
      <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.model/ad/activitydiagram.ecore#//ActivityNode"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="place">
      <eType xsi:type="ecore:EClass" href="../../fr.inria.diverse.sample.petrinetv1.model/model/petrinetv1.ecore#//Place"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition">
      <eType xsi:type="ecore:EClass" href="../../fr.inria.diverse.sample.petrinetv1.model/model/petrinetv1.ecore#//Transition"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlFlowTrace" eSuperTypes="//Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalControlFlow">
      <eType xsi:type="ecore:EClass" href="../../org.gemoc.activitydiagram.sequential.model/ad/activitydiagram.ecore#//ControlFlow"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition">
      <eType xsi:type="ecore:EClass" href="../../fr.inria.diverse.sample.petrinetv1.model/model/petrinetv1.ecore#//Transition"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinNodeTrace" eSuperTypes="//ForkOrJoinNodeTrace"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkNodeTrace" eSuperTypes="//ForkOrJoinNodeTrace"/>
</ecore:EPackage>
